export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'
export const PUT_CATEGORY = 'PUT_CATEGORY'
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY'
export const POST_CATEGORY = 'POST_CATEGORY'
export const POST_CATEGORY_ERROR = 'POST_CATEGORY_ERROR'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'


export const GET_PRODUCTS = 'GET_PRODUCTS'
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR'
