export const GET_PRODUCTS = "GET_PRODUCTS";
export const POST_PRODUCT = "POST_PRODUCT";
export const PUT_PRODUCT = "PUT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";

export const GET_SEARCH = "GET_SEARCH";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const POST_CATEGORY = "POST_CATEGORY";
export const PUT_CATEGORY = "PUT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";


// Tablas intermedia

export const GET_RELATIONS = "GET_RELATIONS";
export const POST_RELATIONS = "POST_RELATIONS";
export const DELETE_RELATIONS = "DELETE_RELATIONS";
export const GET_RELATIONS_BY_ID = "GET_RELATIONS_BY_ID";
export const GET_RELATIONS_CATEGORIES_BY_ID = "GET_RELATIONS_CATEGORIES_BY_ID";
    