export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'
export const PUT_CATEGORY = 'PUT_CATEGORY'
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY'
export const POST_CATEGORY = 'POST_CATEGORY'
export const POST_CATEGORY_ERROR = 'POST_CATEGORY_ERROR'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_BY_SEARCH_TERM = 'GET_PRODUCTS_BY_SEARCH_TERM'
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR'
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const PRODUCT_POST = 'PRODUCT_POST'
export const PRODUCT_PUT = 'PRODUCT_PUT'



export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID'
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'
export const UPDATE_ORDER = 'UPDATE_ORDER'
export const GET_ORDER_QUANTITY = 'GET_ORDER_QUANTITY'

export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const USER_CREATED = 'USER_CREATED'

export const ADD_TO_CART = 'ADD_TO_CART'


